rankss = ["no rank",
        "superkingdom",
        "genus",  
        "species",
        "order",
        "family",
        "subspecies",
        "subfamily",
        "tribe",
        "phylum",
        "class",
        "forma",
        "suborder",
        "superclass",
        "varietas",
        "subclass",
        "kingdom",
        "superfamily",
        "infraorder",
        "subphylum",
        "infraclass",
        "superorder",
        "subgenus",
        "parvorder",
        "superphylum",
        "species group",
        "species subgroup",
        "subtribe",
        "subkingdom"]
